Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision :docker
  config.vm.network "private_network", ip: "192.168.10.12"
  config.vm.synced_folder "../../configuration", "/home/vagrant/configuration"
  config.vm.synced_folder "./logs", "/home/vagrant/logs", create: true
  config.vm.provision :shell, path: "../../scripts/encrypt.sh"
  config.vm.provision :shell, path: "../../scripts/login_registry.sh", args: "no-login"
  config.vm.provision :shell, path: "../../scripts/registry.sh"
end
