Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision :docker
  config.vm.network "private_network", ip: "192.168.10.13"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "../../configuration", "/home/vagrant/configuration"
  config.vm.synced_folder "./logs", "/home/vagrant/logs", create: true
  config.vm.provision "file", source: "../../configuration/daemon.json", destination: "/home/vagrant/daemon.json"
  config.vm.provision :shell, path: "../../scripts/docker_daemon.sh"
  config.vm.provision :shell, path: "../../scripts/login_registry.sh"
  config.vm.provision :shell, path: "../../scripts/just_do_it.sh", run: "always"
end
